CREATE TABLE movies (
    movie_id INT PRIMARY KEY,        -- Unique identifier for the movie
    title VARCHAR(255),              -- Title of the movie
    budget BIGINT,                   -- Budget allocated for the movie
    homepage VARCHAR(2083),          -- URL of the official homepage
    original_language CHAR(2),       -- Original language of the movie (ISO code)
    original_title VARCHAR(255),     -- Original title of the movie
    overview TEXT,                   -- Synopsis or description of the movie
    popularity FLOAT,                -- Popularity score of the movie
    release_date DATE,               -- Release date of the movie
    revenue BIGINT,                  -- Revenue generated by the movie
    runtime FLOAT,                   -- Duration of the movie in minutes
    status VARCHAR(50),              -- Current status of the movie (e.g., Released, Post-production)
    tagline VARCHAR(255),            -- Tagline or catchphrase of the movie
    vote_average FLOAT,              -- Average vote score for the movie
    vote_count INT                   -- Total number of votes received



);

CREATE TABLE movie_cast (
    cast_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    actor_id INTEGER NOT NULL,
    actor_name TEXT,
    character_name TEXT,
    credit_id TEXT,
    gender SMALLINT,
    display_order INTEGER,
    PRIMARY KEY (cast_id, movie_id),  -- Composite primary key
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE
);


CREATE TABLE crew (
    crew_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    credit_id TEXT,
    department TEXT,
    gender SMALLINT,
    melber_id INTEGER NOT NULL,
    job TEXT,
    member_name TEXT,
    PRIMARY KEY (crew_id, movie_id),  -- Composite primary key
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE
);


CREATE TABLE genres (
    genre_id INT PRIMARY KEY,         -- Unique genre id
    name VARCHAR(100) NOT NULL        -- Genre name (example : "Action")
);

CREATE TABLE movie_genres (
    movie_id INT,                     -- Film reference
    genre_id INT,                     -- Genre reference
    PRIMARY KEY (movie_id, genre_id),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres(genre_id) ON DELETE CASCADE
);

CREATE TABLE spoken_languages (
    language_code CHAR(2) PRIMARY KEY, -- Language ISO code
    name VARCHAR(100) NOT NULL         -- Language name
);

CREATE TABLE movie_spoken_languages (
    movie_id INT,                      
    language_code CHAR(2),             
    PRIMARY KEY (movie_id, language_code),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE,
    FOREIGN KEY (language_code) REFERENCES spoken_languages(language_code) ON DELETE CASCADE
);

CREATE TABLE keywords (
    keyword_id INT PRIMARY KEY,       -- Unique keyword id
    name VARCHAR(255) NOT NULL        -- Keyword name
);

CREATE TABLE movie_keywords (
    movie_id INT,                    
    keyword_id INT,                   
    PRIMARY KEY (movie_id, keyword_id),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE,
    FOREIGN KEY (keyword_id) REFERENCES keywords(keyword_id) ON DELETE CASCADE
);

CREATE TABLE users ( 
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL, -- Unique username
    password_hash VARCHAR(255) NOT NULL, -- Hashed password
    role VARCHAR(20) DEFAULT 'user'
);

CREATE TABLE user_movie_interactions (
    user_id INT NOT NULL,                   -- utilisateur
    movie_id INT NOT NULL,                  -- film
    liked BOOLEAN,                          -- TRUE si like, FALSE si dislike, NULL si rien
    watch_status VARCHAR(20) CHECK (watch_status IN ('seen', 'want', 'null')), 
    watch_date DATE,                           -- Date à laquelle l'utilisateur a vu le film, NULL si non vu
    rating INT CHECK (rating BETWEEN 0 AND 5), -- Note sur 5, NULL si aucune note
    PRIMARY KEY (user_id, movie_id),        -- Un utilisateur ne peut interagir qu'une fois avec un film
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id) ON DELETE CASCADE
);

CREATE TABLE playlists (
    playlist_id SERIAL PRIMARY KEY,  -- Unique playlist id
    user_id INT REFERENCES users(user_id), -- refers to user
    name TEXT NOT NULL, -- name of the playlist
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- time created at 
);

CREATE TABLE playlist_movies (
    playlist_movie_id SERIAL PRIMARY KEY,  --unique id
    playlist_id INT REFERENCES playlists(playlist_id) ON DELETE CASCADE, -- refers to the playlist
    movie_id INT REFERENCES movies(movie_id) ON DELETE CASCADE, -- refers to the movies in the playlist
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- added date
);

CREATE TABLE comments (
    comment_id SERIAL PRIMARY KEY,
    movie_id INT REFERENCES movies(movie_id) ON DELETE CASCADE,
    user_id INT REFERENCES users(user_id) ON DELETE CASCADE,
    comment_text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);